# Generated by Django 4.2.3 on 2023-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.CharField(max_length=255)),
                ('stadium', models.CharField(max_length=255)),
                ('rivals', models.CharField(max_length=255)),
                ('coach', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('ground_url', models.CharField(max_length=255)),
                ('jersey_one', models.CharField(max_length=255)),
                ('jersey_two', models.CharField(max_length=255)),
                ('jersey_three', models.CharField(max_length=255)),
                ('goalkeeper', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Clubs',
                'ordering': ('name',),
            },
        ),
    ]
