# Generated by Django 4.2.3 on 2023-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='goalkeeper',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='jersey_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='jersey_three',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='jersey_two',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
