# Generated by Django 4.2.3 on 2023-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_goalkeeper_alter_club_jersey_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='capacity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='sponsor_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='sponsor_two',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
