# Generated by Django 4.2.3 on 2023-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_capacity_club_sponsor_one_club_sponsor_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
