# Generated by Django 4.2.3 on 2023-07-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
