# Generated by Django 4.2.3 on 2023-07-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='backdrop_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
