# Generated by Django 4.2.3 on 2023-07-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_backdrop_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='backdrop_url',
        ),
    ]
